spring:
  application:
    name: JobSwipe
  datasource:
    url: jdbc:postgresql://db.ewaacqxaozyuloyqzcou.supabase.co:5432/postgres
    username: postgres
    password: TIEhn2qmUtofssG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            jdbc:
              batch_size: '10'
            order_inserts: 'true'
  flyway:
    enabled: false

server:
  port: 4196

security:
  jwt:
    secret-key: i7QwDugB3oSCG4gOtiRmq42bK3UrCkB6uqVBRTUTVfQ=
    expiration-time: 3600000

google:
  api-key: "XNqNDXqXXj7rjesXOBWSRki+NbrLcIzq7AIco1UHx3I="
  cx: "f2aad16898c394f74"