spring:
  application:
    name: JobSwipe
  datasource:
    url: jdbc:postgresql://localhost:5432/job-swipe
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: '10'
        order_inserts: 'true'
  flyway:
    enabled: false

  cloud:
    aws:
      credentials:


      region:


server:
  port: 4196

security:
  jwt:
    secret-key: i7QwDugB3oSCG4gOtiRmq42bK3UrCkB6uqVBRTUTVfQ=
    expiration-time: 86400000

google:
  api-key: "AIzaSyBnodsjCkI7RMaHcVC1tKqeI_TYQtbv-5E"
  cx: "f2aad16898c394f74"